# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    branches: [ master ]
    types:
      - closed
jobs:
  build-and-publish-lib:
    uses: kne-union/actions/.github/workflows/publish-libs-no-example-workflow.yml@master
    secrets: inherit
    with:
      package_name: '@kne/mini-resume'
